version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  postgres:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chatAdmin
      POSTGRES_PASSWORD: pass
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - 8080
    depends_on:
    - rabbitmq
    - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - chat
    ports:
    - "8080:8080"
